---
title: "Network Analysis of Game of Thrones "
output: html_notebook
---


###This Article will now consist of the plotting Directed Acyclic Graphs of relationships 

The previous article consisted of the Data Processing,data scraping and preparing the data to be used in making Network DAGs.

```{r,warning=FALSE,message=FALSE}
require(igraph)

```
```{r}
#making a new data frame consisting of all people in House Frey
characters_Frey <- characters %>%
  filter(name %in% c("Emmon Frey", "Cleos Frey", "Tywin Frey", "Willem Frey", "Lyonel Frey", "Tion Frey", "Walder Frey son of Emmon", "Amerei Frey", "Lancel Lannister", "Merrett Frey", "Walda Frey daughter of Merrett", "Walder Frey son of Merrett", "Marissa Frey", "Roslin Frey", "Olyvar Frey", "Willamen Frey", "Benfrey Frey", "Perwyn Frey"))

net_Frey <- net %>%
  filter(source %in% characters_Frey$name | target %in% characters_Frey$name)

#adding line types and arrows i.e edges
net_Frey$lty <- "solid"
net_Frey$arrow <- ifelse(net_Frey$type == "spouse", 3, 2)

net_Frey <- net_Frey[net_Frey$type != "father/mother", ]
net_Frey <- rbind(net_Frey,
                  c("Perra Royce", "Walder Frey", "spouse", "#E7298A", "solid", 3),
                  c("Amarei Crakehall", "Walder Frey", "spouse", "#E7298A", "solid", 3),
                  c("Bethany Rosby", "Walder Frey", "spouse", "#E7298A", "solid", 3))

characters_Frey <- characters %>%
  filter(name %in% net_Frey$source | name %in% net_Frey$target) %>%
  arrange(name)


#?graph_from_data_frame to search on this function
graph_Frey <- graph_from_data_frame(net_Frey, directed = TRUE, vertices = characters_Frey)


```

Now we will generate Directed Acyclic Graphs using igraph package

```{r,out.height=15,out.width=20}
#using pdf to generate pdf graphics
pdf("family_frey_tree.pdf", width = 20, height = 15)
#Plotting the DAG for Frey family
plot(graph_Frey,
     layout = layout_with_lgl,
     vertex.label = gsub(" ", "\n", V(graph_Frey)$name),
     vertex.shape = V(graph_Frey)$shape,
     vertex.color = V(graph_Frey)$color, 
     vertex.size = (V(graph_Frey)$popularity + 0.5) * 5, 
     vertex.frame.color = "gray", 
     vertex.label.color = "black", 
     vertex.label.cex = 0.8,
     edge.arrow.mode = E(graph_Frey)$arrow,
     edge.arrow.size = 0.5,
     edge.color = E(graph_Frey)$color,
     edge.lty = E(graph_Frey)$lty)

legend("topleft", legend = c(as.character(color_vertices$house), as.character(colors_edges$type)), pch = 19,
       col = c(color_vertices$color, colors_edges$color), pt.cex = 2, cex = 1, bty = "n", ncol = 1)


```

---------------


###House Stark Tree

```{r}
characters_Stark <- characters %>%
  filter(house == "House Stark")

net_Stark <- net %>%
  filter(source %in% characters_Stark$name | target %in% characters_Stark$name)

net_Stark <- net_Stark[net_Stark$source != "Unnamed mother", ]

net_Stark$lty <- ifelse(net_Stark$source == "Lyanna Stark" & net_Stark$target == "Jon Snow", "dotted", "solid")
net_Stark$lty <- ifelse(net_Stark$source == "Sansa Stark" & net_Stark$target == "Ramsay Bolton", "dotted", net_Stark$lty)
net_Stark$lty <- ifelse(net_Stark$source == "Rhaegar Targaryen" & net_Stark$target == "Jon Snow", "dotted", net_Stark$lty)
net_Stark$lty <- ifelse(net_Stark$source == "Talisa Stark" & net_Stark$target == "Robb Stark", "dotted", net_Stark$lty)

net_Stark$arrow <- ifelse(net_Stark$type == "spouse", 3, 2)

characters_Stark <- characters %>%
  filter(name %in% net_Stark$source | name %in% net_Stark$target) %>%
  arrange(name)

graph_Stark <- graph_from_data_frame(net_Stark, directed = TRUE, vertices = characters_Stark)


```

Stark Family Tree 
```{r}
pdf("family_tree_Stark.pdf", width = 20, height = 15)
plot(graph_Stark,
     layout = layout_with_lgl,
     vertex.label = gsub(" ", "\n", V(graph_Stark)$name),
     vertex.shape = V(graph_Stark)$shape,
     vertex.color = V(graph_Stark)$color, 
     vertex.size = (V(graph_Stark)$popularity + 0.5) * 5, 
     vertex.frame.color = "gray", 
     vertex.label.color = "black", 
     vertex.label.cex = 0.8,
     edge.arrow.mode = E(graph_Stark)$arrow,
     edge.arrow.size = 0.5,
     edge.color = E(graph_Stark)$color,
     edge.lty = E(graph_Stark)$lty)
legend("topleft", legend = c(as.character(color_vertices$house), as.character(colors_edges$type)), pch = 19,
       col = c(color_vertices$color, colors_edges$color), pt.cex = 2, cex = 1, bty = "n", ncol = 1)


```

---------------


###Lannister Family Tree

```{r}
characters_Lannister <- characters %>%
  filter(house == "House Lannister") %>%
  filter(!name %in% c("Margot Lannister", "Tya Lannister"))

net_Lannister <- net %>%
  filter(source %in% characters_Lannister$name | target %in% characters_Lannister$name)

net_Lannister$lty <- ifelse(net_Lannister$source == "Jaime Lannister" & net_Lannister$type == "father/mother", "dotted", "solid")
net_Lannister$type <- ifelse(net_Lannister$source == "Jaime Lannister" & net_Lannister$type == "father/mother", "father", net_Lannister$type)
net_Lannister[net_Lannister$source == "Jaime Lannister" & net_Lannister$type == "father", "color"] <- "#1B9E77"

net_Lannister$arrow <- ifelse(net_Lannister$type == "spouse", 3, 2)

characters_Lannister <- characters %>%
  filter(name %in% net_Lannister$source | name %in% net_Lannister$target) %>%
  arrange(name)

graph_Lannister <- graph_from_data_frame(net_Lannister, directed = TRUE, vertices = characters_Lannister)


```

Plotting the Graph
```{r}
pdf("family_tree_Lannister.pdf", width = 20, height = 15)
plot(graph_Lannister,
     layout = layout_with_lgl,
     vertex.label = gsub(" ", "\n", V(graph_Lannister)$name),
     vertex.shape = V(graph_Lannister)$shape,
     vertex.color = V(graph_Lannister)$color, 
     vertex.size = (V(graph_Lannister)$popularity + 0.5) * 5, 
     vertex.frame.color = "gray", 
     vertex.label.color = "black", 
     vertex.label.cex = 0.8,
     edge.arrow.mode = E(graph_Lannister)$arrow,
     edge.arrow.size = 0.5,
     edge.color = E(graph_Lannister)$color,
     edge.lty = E(graph_Lannister)$lty)
legend("topleft", legend = c(as.character(color_vertices$house), as.character(colors_edges$type)), pch = 19,
       col = c(color_vertices$color, colors_edges$color), pt.cex = 2, cex = 1, bty = "n", ncol = 1)


```

-----------

###Baratheon House
```{r}
characters_Baratheon <- characters %>%
  filter(house == "House Baratheon") %>%
  filter(!name %in% c("Orys Baratheon", "Gowen Baratheon"))

net_Baratheon <- net %>%
  filter(source %in% characters_Baratheon$name | target %in% characters_Baratheon$name)

net_Baratheon$lty <- ifelse(net_Baratheon$source == "Jaime Lannister" & net_Baratheon$type == "father/mother", "dotted", "solid")
net_Baratheon$type <- ifelse(net_Baratheon$source == "Jaime Lannister" & net_Baratheon$type == "father/mother", "father", net_Baratheon$type)
net_Baratheon[net_Baratheon$source == "Jaime Lannister" & net_Baratheon$type == "father", "color"] <- "#1B9E77"

net_Baratheon$arrow <- ifelse(net_Baratheon$type == "spouse", 3, 2)

characters_Baratheon <- characters %>%
  filter(name %in% net_Baratheon$source | name %in% net_Baratheon$target) %>%
  arrange(name)

graph_Baratheon <- graph_from_data_frame(net_Baratheon, directed = TRUE, vertices = characters_Baratheon)

```



---------------------


 
###House Targaryen 

```{r}
characters_Targaryen <- characters %>%
  #filter(house == "House Targaryen")
  filter(name %in% c("Daenerys Targaryen", "Rhaegar Targaryen", "Viserys Targaryen", "Aerys II Targaryen", "Jaehaerys II Targaryen", "Aegon V Targaryen", "Duncan Targaryen", "Rhaelle Targaryen"))

net_Targaryen <- net %>%
  filter(source %in% characters_Targaryen$name | target %in% characters_Targaryen$name)

net_Targaryen$lty <- ifelse(net_Targaryen$source == "Maron Martell" & net_Targaryen$target == "Daenerys Targaryen", "dotted", "solid")
net_Targaryen$lty <- ifelse(net_Targaryen$source == "Rhaegar Targaryen" & net_Targaryen$target == "Jon Snow", "dotted", net_Targaryen$lty)
net_Targaryen$arrow <- ifelse(net_Targaryen$type == "spouse", 3, 2)

characters_Targaryen <- characters %>%
  filter(name %in% net_Targaryen$source | name %in% net_Targaryen$target) %>%
  arrange(name)

graph_Targaryen <- graph_from_data_frame(net_Targaryen, directed = TRUE, vertices = characters_Targaryen)

```




```{r}
union_edges <- rbind(net_Arryn, 
                     net_Baratheon,
                     net_Frey,
                     net_Greyjoy,
                     net_Lannister,
                     net_Martell,
                     net_Stark,
                     net_Targaryen,
                     net_Tully,
                     net_Tyrell) %>%
  .[!duplicated(.), ]

union_edges <- rbind(union_edges,
                     c("Roose Bolton", "Ramsay Bolton", "father",	"#1B9E77", "solid",	2))

union_edges1 <- union_edges[union_edges$type == "spouse", ]
union_edges1$target <- union_edges[union_edges$type == "spouse", "source"]
union_edges1$source <- union_edges[union_edges$type == "spouse", "target"]

union_edges2 <- rbind(union_edges[union_edges$type != "spouse", ],
                      union_edges[union_edges$type == "spouse", ],
                      union_edges1)


```

